FROM python:3.6

RUN apt-get update

ADD ./resources/safebox-nleaser.tar.gz .
COPY ./workers/sentence_import/dist/sentence_import*.whl .

# Install safebox
WORKDIR safebox-nleaser
RUN pip3 install Cython
RUN python setup.py install
WORKDIR /

RUN pip3 install sentence_import*.whl

ENV ENV=development
ENV HOST=docker

ENTRYPOINT ["python", "-m", "workers.sentence_import"]

