FROM python:3.6

RUN apt-get update

ADD ./resources/safebox-nleaser.tar.gz .
COPY ./workers/wordcloud_create/dist/wordcloud_create*.whl .

# Install safebox
WORKDIR safebox-nleaser
RUN pip3 install Cython
RUN python setup.py install
WORKDIR /

RUN pip3 install wordcloud_create*.whl

ENV ENV=development
ENV HOST=docker

CMD ["python", "-m", "workers.wordcloud_create"]

