FROM python:3.6

RUN apt-get update

ADD ./resources/safebox-nleaser.tar.gz .
COPY ./workers/ner_extract/dist/ner_extract*.whl .

# Install safebox
WORKDIR safebox-nleaser
RUN pip3 install Cython
RUN python setup.py install
WORKDIR /

RUN pip3 install ner_extract*.whl
RUN python -m spacy download en_core_web_trf
RUN python -m spacy download pt_core_news_lg

ENV ENV=development
ENV HOST=docker

CMD ["python", "-m", "workers.ner_extract"]

