FROM python:3.6

RUN apt-get update

ADD ./resources/safebox-nleaser.tar.gz .
COPY ./nleaser_workers/ngrams_create/dist/ngrams_create*.whl .

# Install safebox
WORKDIR safebox-nleaser
RUN pip3 install Cython
RUN python setup.py install
WORKDIR /

RUN pip3 install ngrams_create*.whl

ENV ENV=development
ENV HOST=docker

CMD ["python", "-m", "workers.ngrams_create"]

